---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./config-grafana-pvc.yaml
  - ./helmrelease-grafana.yaml
  - ./helmrelease-mosquitto.yaml
  - ./mosquitto-config-pvc.yaml
  - ./mosquitto-data-pvc.yaml
