---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: n8n-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        N8N_BASIC_AUTH_USER: "{{ .N8N_BASIC_AUTH_USER }}"
        N8N_BASIC_AUTH_PASSWORD: "{{ .N8N_BASIC_AUTH_PASSWORD }}"
  dataFrom:
    - extract:
        key: n8n
  refreshInterval: 5m
