apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: n8n
  namespace: default
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: n8n-secrets
    creationPolicy: Owner
  data:
    - secretKey: N8N_BASIC_AUTH_USER
      remoteRef:
        key: n8n-basic-auth-user
    - secretKey: N8N_BASIC_AUTH_PASSWORD
      remoteRef:
        key: n8n-basic-auth-password
