ansible_become_pass: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15nyeuq0zlhyu80tytvwhjdhmpa5mwnclm454cc0trt7ezxrnk37shpeefh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiNFpwVUJFenczdUc5b0xp
            RzFSY2EyQ0NycXhmQ0poRkZrd1g4VU9DL3hnCmcwc2VINlZ0NmRpMDhTWk9ZVGJz
            L2JJWkMrdXl0d2lxT3h0ZDRQbGFtZHcKLS0tIGFIampHa0pwL0cvc1ZFTDdCR3VJ
            NUQvV0IvYkkzbjZYRVFYSGp0YURsZHcKyzcpQ6Xf7b6zU0t7F1Wqk45MJxsIVC1G
            ZydZwlc/y0FDikje4+NEmxMf9aEY/za4m3C2DD4I0QTh+DcgU2xuSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-10T03:07:42Z"
    mac: ENC[AES256_GCM,data:fnFShCJhZAkS+sENJtVoDXs8Q233AELkGL/PpI8uAnVHdyiFADLUjlbXAzBCLxwIClAyf/MDUqZlWFyYboApC1Tmxjluj2S0l/0hVeIxSdooLOLaBclCRi90EKSg9zYYXNy9wPTtvcjLzQLvf21e737NVxaj2vMH0gpZSk486BA=,iv:pbcg+MI1Hx5a26u3R1sf4riZsGRyt3LKA1GGMx+hbqE=,tag:JEoxKeUps/vWoKwnC7Tm9A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
