ansible_become_pass: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15nyeuq0zlhyu80tytvwhjdhmpa5mwnclm454cc0trt7ezxrnk37shpeefh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHR2ZMbkFIT1lzVldXT1pq
            NUNvN01mdkRTcEE5WTVId2swQm9nZVEzejNzCkpRTWRYVXlOa3pYTUhlZWZYWmZY
            RnJQaEJiWXVwN2o4ejllTjNTZ01vT1kKLS0tIFJzekJDWE1NRDVGcU9lSGppV0pr
            ZlJ0NmpDUWx5dHRvMjZZVHpYbG5icEEKLg9LLziwcS8WQcU09trJmlt0WA7xaPWs
            4W60F+AiezohZN9iwj3ZpXDXRgeltjaanubQ71kdvvjm9A8mrb8k1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-09T20:44:42Z"
    mac: ENC[AES256_GCM,data:TC7FqqbmRL7fiLET38w1mFi1RNnQN2SxxbsiKReeDWDrO6adiHlAGYTWoqUcgnOEkE9MUUbJeNDN6Stz8pI+wpFdhQHcMBEs56fu0LteoduxMpBKSqx8AbWhx+JR0xK1eSZJKmqrHewny2InlP5hnNj1mtno5l4IsR+QwiDszEc=,iv:mFYKWAzXDoNUgBj3CSm51sTwGp5pboiMBn1pQi+P8TY=,tag:p9wwYg/ClE0TSVnYa5wkow==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
