ansible_become_pass: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15nyeuq0zlhyu80tytvwhjdhmpa5mwnclm454cc0trt7ezxrnk37shpeefh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmYjA3RklyV0g0MU5KNlJ2
            QWlXMHVwUk5jblM4RERtMklOYTJ6bnBBWlNNCnMwWG9OenRjak5KbWdIazVKZDE5
            aC9OZWl1SnBaWnpMOTZiSWRvWnZLdHMKLS0tIDZPUHFoWmNKNEhnZEtaeFhicm1Q
            OHQvaGJ5cFQ4N09Od2ZwdU8rMWgwc00KySnnThZSWPStRuXd21SQCes8fN1hBhqO
            2n2v61e2HwCURylbhJrCv73McixJjnYPJG8lNxUjS2TAMcvqvkveRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-10T03:07:42Z"
    mac: ENC[AES256_GCM,data:ABN6a+hXX8AGjhjDze+p08TJ1TUUCz9bW/IAVIDhzUOErZGKtqW7egQaQDKrUCgq9CzF/IoMg1rP3B/3T+FObp24AGwWNejPkluHfS82XLeAiCIqXhm2iXizr/6f4rCJYJCw7KTiEoXMWwQgbtsNjB1UmoEMpMYOHf2T7JZ9EUw=,iv:JAOKkaD/Ec9NS2+UffP5WKP6Hu3pONPc8N7KBqUFSD4=,tag:04LUZYuT+6q6uWL9Huks3g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
