ansible_become_pass: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15nyeuq0zlhyu80tytvwhjdhmpa5mwnclm454cc0trt7ezxrnk37shpeefh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlRzA3NHI1SkVHaDA1c013
            UWduQzN3dldjZ24vTmExTE9qcmFZUVRMMEMwClBGVzNFTUVOUSt4dEJVVkFJbVdB
            MTBnUlBEeVhpTnBTZnp0enJSYWZYTFkKLS0tIGhzOFBQSEtrTTdROUVGKzFBZUVT
            d1RkTUFXSWpLV2QydTVqWit0QTdTbUEKmejkGvVNdmxaksdQQhw9typCLXx3wXEQ
            cy7f2tO2HtayB3FYWoZzaDYGZ0HFD5RMIlUVdKhCkHePV/YuHNF+hw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-09T20:44:42Z"
    mac: ENC[AES256_GCM,data:nXM7rMn6QvRBROZvZ+btS0jvuZpdjDSQEZxpER0zt0J46Nz3OmZJYA0CZUDQPqxPd7XDgPcPMmVo5JlDL+cB33gND/glCeQKsXb97lQ4g0vh7R1LHtoo/3W1xGqBDgJjWRxulZce4CWmEFIHhOx9AiIpEeSzQxbe6jD9kw73eyw=,iv:ijBgxdaxznxtGSYxv6AoiIAvm3vXEQlszyDF6sQu0Gg=,tag:u7jw+FcFHI4mZUaVwtmBKw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
