---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mousesearch
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mousesearch-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        QUART_SECRET_KEY: "{{ .QUART_SECRET_KEY }}"
        MAM_ID: "{{ .MAM_ID }}"
        TORRENT_CLIENT_USERNAME: "{{ .TORRENT_CLIENT_USERNAME }}"
        TORRENT_CLIENT_PASSWORD: "{{ .TORRENT_CLIENT_PASSWORD }}"
  dataFrom:
    - extract:
        key: mousesearch
  refreshInterval: 5m
