apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-password: ENC[AES256_GCM,data:nuNxkNnH6Ss=,iv:1Atd7Nj6zqDqd8KXRTIts0FHkgou9XU0UJUEwt7+WN4=,tag:Hmagclg47hA+YgJOtXqhvg==,type:str]
    admin-user: ENC[AES256_GCM,data:GoiwbOE=,iv:VY/foetTHJKgbm94gLX9qLCwLzheoad/p2UU8vFOqLw=,tag:R/vtwwIv9q15wT3wWhUZ+A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15nyeuq0zlhyu80tytvwhjdhmpa5mwnclm454cc0trt7ezxrnk37shpeefh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRMFpHRzh0cG5WclV5Ky9l
            cnlhRkhIR0N1bEdvdVI1VW9FaUZmSi92d2c4CnFZdCt5N0dsejRHZXZhZnJhOEZG
            dnRBcEEwVVRldWE3V201RldTU3NXM1UKLS0tIHMxeXk5WlBQMjdFTW1oZng2QjVG
            Y3I4WWh3MVltUlk2d3lZZFlGQWlEdW8KDVWCncefecjTJwB5OzCQDQkeXKKqqwZm
            uFC9Szgn7QISK+OgQu0aAWMLT+noDpwjWGI8b9NETrJPKchpxKAeiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-10T03:08:17Z"
    mac: ENC[AES256_GCM,data:BJb+Dq5cYkG86fH/XizZXQw4f1HJjbR9Jz17OHL6Swv4o8PVPqnkVEhpODW+5pnhAYOSLyadW0qvZGzI1QTYY6kXuJwESboNP1dTg0ElksaiaPS8lV8F2w5bZ+dLY6KaojZmD/zMLDgEyEi+JgjTS7oherSoF/WMYKur6LyRl1M=,iv:wSUvHBHx7FSymBs7C6pWehW6ZyJdEHj2DpiqGn8KFEs=,tag:2Hkc1hmiPyvXjvedX88czg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
