---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app dailytrace-db
  namespace: default
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: dailytrace-db
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      database:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: timescale/timescaledb
              tag: 2.22.1-pg17
            envFrom: &envFrom
              - secretRef:
                  name: dailytrace-db-secret
            resources:
              requests:
                cpu: 50m
                memory: 100Mi
              limits:
                memory: 750Mi
        pod:
          securityContext:
            runAsUser: 1024
            runAsGroup: 100
            fsGroup: 100
            fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: database
        ports:
          http:
            port: &port 5432
    serviceMonitor:
      app:
        enabled: true
        endpoints:
          - port: http
    persistence:
      data:
        enabled: true
        type: nfs
        server: 192.168.10.3
        path: /volume1/cluster/dailytrace-db
        globalMounts:
          - path: /var/lib/postgresql/data
      restore:
        enabled: true
        type: nfs
        server: 192.168.10.3
        path: /volume1/cluster/db-restore
        globalMounts:
          - path: /restore
