---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app dailytrace-db
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      replicas: 1
      strategy: RollingUpdate
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: timescale/timescaledb
      tag: 2.22.0-pg17
    envFrom: &envFrom
      - secretRef:
          name: dailytrace-db-secret
    service:
      main:
        ports:
          http:
            port: &port 5432
    serviceMonitor:
      main:
        enabled: true
    persistence:
      data:
        existingClaim: dailytrace-db-v1
        mountPath: /var/lib/postgresql/data
        enabled: true
        subPath: pgdata
      restore:
        enabled: true
        type: nfs
        server: 192.168.10.3
        path: /volume1/cluster/db-restore
        mountPath: /restore
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 750Mi
