---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dailytrace-db-v1
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 15Gi
  storageClassName: longhorn
