apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:evkt2wCK3f/G4wIQ0HYz5vs6N7XGykic,iv:SENteK5IyXtj504W1c2EjWLvjc/FGwYLqHdzxDOy/kQ=,tag:WDdNHYXKqIJRUXim3FnuPw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15nyeuq0zlhyu80tytvwhjdhmpa5mwnclm454cc0trt7ezxrnk37shpeefh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2TGNjSyttZGY5eEdWMkJw
            VnVibWVYV2lmNExKTnhjMVg2RTNyOEp0UlJvCmg1ME1IMXhZTll0Zm1mdVRvV1di
            Y1BJT2VIMldWQy82dWJKcHBBR0ticFEKLS0tIGhlNVBQajBPUTJnKzVEcyt6Tlhj
            SEUrRXA4K05za2p6cFJrMWxuWTdDZ3cKF2I+oQwfdycLlrgwcNR6iDAXoK0leLkn
            n99l7rDjI+IncQD49CDFUqHVwL7GUzUJXaV38loIgEQbd9fgQTth8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-10T03:08:15Z"
    mac: ENC[AES256_GCM,data:GIPU+YU4e4+5AXxgyqPwqz9Ykm4HBY+K8h3IUsEdZ27Pe6qgLZLfw7y1aRduqHsDCX+WMsETRH+e04JQV0fHvqTJJRiiILkyePvH8CZEU12ez9wp/LnGl7WWQakUScRLTf16A28IHLL0BW8EgTZ99HBfj7EWiHarbISbtJsX6QU=,iv:/D9vTKOK2z06SQ5Ev3gpuPqgf6+j603F+8xbAh3DRJw=,tag:udeK/pHGZclTOyNO/ObR6A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
