apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:dlGmK2w77h1nBqc/Tzks3nxvhw0cxjfz,iv:ilb9jrqnXogsc7Wl/M7zmQi64utPvj9EQ6RdeluH+kU=,tag:g1tURGsboGJwN0YpP2dZmg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15nyeuq0zlhyu80tytvwhjdhmpa5mwnclm454cc0trt7ezxrnk37shpeefh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsd0FHMU0zS0Nxa2NOUEJU
            dWxBblliRG9TK0VLTXB1WjdieWEvek5NTno0ClIrRU9CVE4vM1FvNnA2cDZ6Q1ZL
            eStlYTRQY0U1U1EybEdiTnhsczgrcjQKLS0tIDB1SWczN2hta0VrdjhvV1lHTHFJ
            Uk9EUTF0T2xNS2NndHVRY0RZY1RsMTQKo5uxd/uW329CetXReJ5lvLA3jQFwHYFK
            sKqNbOmca4bO9nj2nCCyuTkZYfhatSr0+nt6X02B02gDMW1O3V426A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-09T20:45:15Z"
    mac: ENC[AES256_GCM,data:MH3pFUxhapjcjvYBSXuELGxwcAPfMNkwUc6s0Rq8ZzyeYRnEvIq2uXqosQgYJHU8tN4nLp2m58LTBDjMz4jGVJdYNuWOXbVi99u2rNinOKAl3LrGqpqNbFcWSFz+vJzm2E8asRCPMnSUf1WMGBNPyNztDLDPhWB58EGiUwLx2VA=,iv:sLlnR52MnZL1xXi7Dcgjd8L/FhCMmViuXx90tjMQqns=,tag:Em25eQUEunMn9kBeOVO3Hg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
