apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:uleCQELCjxDFhxe8gzKXvxszegpWHZfQ,iv:3PuTPr1D80VdDoAqAvhBHmZ4PDMH0Jl5a8PclsmBWl0=,tag:eTbszD3LcoBHdKVNjvAxWg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15nyeuq0zlhyu80tytvwhjdhmpa5mwnclm454cc0trt7ezxrnk37shpeefh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAycTduM1JJbnNHYlBtMHVp
            c3liRGpqTEhVY2R4TVBDNkpZeDVJa3hqL1NFCjJuVWg4MlRpTlBaLzhSSUQ0RDA5
            enlWdjhDM2VZYkdtRG5hSDJ3MzhYSVEKLS0tIHpwd3FrM2N5MDhrcHY0TTA1Rk9m
            ODBpcXBGNGxudHRJdEREdjJ6bjBkYUkKbTzWh/IkjxmdpEMhjEGKUL/jzu2Zx/mr
            IWhyXKKiz7GuwA4nUHfM1e/Oky0/aW8kcA/xmoRcIwE5WOyX05QoSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-09T15:48:25Z"
    mac: ENC[AES256_GCM,data:j/3/TWvEaI34uI1cay+sE1s+l11cTH8gaow6KQlVJ5RxtJsdwEsXhkQHoYWOPYZ3lPM9sQiXQDaj6JeiXEWs9CBXiplvOTd6y+zcLQhnWb/mDamcLChdN/wktVYb/lshB/xP0MvBuKF0oGdZXG7NbvAzKCS3Ovc08Fe/IF2dwqE=,iv:1uOnz5oyot8jV3NlNRIkHWYTTAB21xtdOzMWyoRZ8D4=,tag:Vya1Xo/zSd6v35zdskGXvg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
