---
kubernetes:
  children:
    master:
      hosts:
        nostromo:
          ansible_user: root
          ansible_host: 192.168.10.137
        atlantis:
          ansible_user: root
          ansible_host: 192.168.10.6
        discovery:
          ansible_user: root
          ansible_host: 192.168.10.4
    worker:
      hosts:
        kube1:
          ansible_user: root
          ansible_host: 192.168.10.150
        kube2:
          ansible_user: root
          ansible_host: 192.168.10.151
        kube3:
          ansible_user: root
          ansible_host: 192.168.10.153
        kube4:
          ansible_user: root
          ansible_host: 192.168.10.155
        kube5:
          ansible_user: root
          ansible_host: 192.168.10.71
        kube6:
          ansible_user: root
          ansible_host: 192.168.10.72
        kube7:
          ansible_user: root
          ansible_host: 192.168.10.73
        kube8:
          ansible_user: root
          ansible_host: 192.168.10.74
        galactica:
          ansible_user: root
          ansible_host: 192.168.10.8
        serenity:
          ansible_user: root
          ansible_host: 192.168.10.9
