---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app sonarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.0.4
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5

  values:

    image:
      repository: ghcr.io/onedr0p/sonarr
      tag: rolling@sha256:bbfcda0754272515ce12972924652699934074b46b11d27bc515c8ea5fb870f5
    env:
      TZ: ${TIMEZONE}
      SONARR__INSTANCE_NAME: Sonarr
      SONARR__PORT: &port 80
      SONARR__APPLICATION_URL: "https://{{ .Release.Name }}.${SECRET_DOMAIN}"
      SONARR__LOG_LEVEL: info
    service:
      main:
        ports:
          http:
            port: *port
    envFrom:
      - secretRef:
          name: sonarr-secret
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
          hajimari.io/icon: "movie-roll"
        hosts:
          - host: &host-release "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
          - host: &host-custom "sonarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host-release
              - *host-custom

    podSecurityContext:
      runAsUser: 1026
      runAsGroup: 65537
      fsGroup: 65537
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 100

    persistence:
      config:
        enabled: true
        type: nfs
        server: 192.168.10.3
        path: /volume1/cluster/sonarr
        mountPath: /config
      downloads:
        enabled: true
        type: nfs
        server: 192.168.10.3
        path: /volume1/downloads/complete/tv
        mountPath: /downloads
      tv:
        enabled: true
        type: nfs
        server: 192.168.10.3
        path: /volume2/share/videos/tv
        mountPath: /tv
      backup:
        enabled: true
        type: nfs
        server: 192.168.10.3
        path: /volume1/cluster/backup/sonarr
        mountPath: /backup
    resources:
      requests:
        memory: 500Mi
        cpu: "1.5"
      limits:
        memory: 500Mi
        cpu: "3"
