---
# Allow HTTPRoutes in app namespaces (proxied apps) to send traffic to the
# authentik-server Service, which runs the embedded proxy outpost.
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: default-to-authentik-server
  namespace: security
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: default
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: media
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: observability
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: longhorn-system
  to:
    - group: ""
      kind: Service
      name: authentik-server
