apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:B9yV/XFkXL6yZGzHz126D7XNTrXDolSbZtvOyaWpa+715IBF3jvXAg==,iv:Jxgnm/+uwDJAOSpHrI6Cv7NdjI501CNuLXcyLcCJHYc=,tag:EK3M/tgkFXn8G0RxB3H9EQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15nyeuq0zlhyu80tytvwhjdhmpa5mwnclm454cc0trt7ezxrnk37shpeefh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxVENueU9uaVBTL2JtWlBJ
            eUErZHlhMERDb0NtcjlRdEp6Zjh2ei9sWG1BCnZvczFqQ1N1T1ltWUEzRm40bGlG
            WWRZWFhhQVZoQUcvZCtyaFRlaS92ZlUKLS0tIEdQdFJtMGpndXN5aVpYSWFXenFV
            N2hiQ2lUYlhZdXg2UDdEb1RhN0oxc2cKIgng69TxeOh6kZVX8/EnP7nNyGhN/dzU
            NtuOO6Cmm62kOd1iPSBvR9mynt8HxwcyRBQpAGo/wgN8t5i2oMvVLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-09T20:45:15Z"
    mac: ENC[AES256_GCM,data:tk6zuOkYhNEZ+nNBx7i0swX7ZIl1/TQdnQxU7R6Rdv93M/KhtAGlqciFIf41kAqTVJMMqUce1v3Hq+PeiuwSMRULg7eGoD4KcXRTGK0B3A7o9qZOXWCBcWiMLPf4K3O4jIf/LOrnBVZ9RgzhLi0lrWYtFq7XVx5GlxoFZUc86DI=,iv:Sp9Xu6AAXABCuYRr47+P4/SGD+r0CziU4PNEoqiAJ9Q=,tag:rLfnjAwZj3u6d64P2SQ/cA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
