apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:mapHTNhbTikO9EE3N9MDJOUEsAAmJkK5LB+6j4zXRK/Uy00UCAdyhQ==,iv:RsW+zxnf0QtObboK+2VqcUlcZOCalB12KPlh5EnhtlQ=,tag:ebs1VQcFvt2shI25cZLTfw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15nyeuq0zlhyu80tytvwhjdhmpa5mwnclm454cc0trt7ezxrnk37shpeefh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkblliVm5WN3NRaFcrOFFo
            Nnd6YUhCNzVINGUzdkI2RUhOaWFvYlJNVTJVCitRemxlSXNveGEveUhlenRVK3Mw
            cHc1L0NSbzArMjllbEcrV2svL3ZJN00KLS0tIHNLMVBjQ3U4ZUFNZlJPQWYyVXpo
            R1Z4KzJEeHhNVWZ2bnBmQlNhTVZaTzQKXoNPkEVZL1hGXpYjZAQDU6eR/D1KARR7
            x/XZzj3pt66ZH5lELKGJe/fFZywF/iJyVrWj0yHBATI57pAVAkhW5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-09T15:48:25Z"
    mac: ENC[AES256_GCM,data:NNi4Od4hDFT8sJNUy5etj9jmc2ev2hUO8KAFSZn4usP3TFMv95EpKVRTC43FZqcNV7GU9Bsh1nO017kyRrtoGX4NcU03EwtqXE+Bwki1fJAWbiAcjb4y7bZW7fWS+I8Z3hG7HisiUSpK6bo6997vF8MUonyuj+CsmZ7VO7gEt8k=,iv:u47HuFpKv6JKNBWPEqSxq39uz4vtEVZs7eKKa3K0H+w=,tag:8FqgPfEIhV1q/rAusaNvQw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
