apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:Zwi9O7gpjByIdI84yGiEBh3GmhrEZrpE/Tv8Euwd+gwv741i7EHkEQ==,iv:TLAxZMM6Gs19RMTff2ZZYrGmFl+oGZ1k78rwpCM+tLc=,tag:yJxqpN4zkmG0tQnuNk/XZw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15nyeuq0zlhyu80tytvwhjdhmpa5mwnclm454cc0trt7ezxrnk37shpeefh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPZnNvRWVKcC92eEZOUkkv
            T0t3ZW1vNExFcUx1MUhIeWFwUzVkZ3ROblZFCnZBZEZqUlloQUhXN3htMmEzUjlo
            NjNnb25PWGN0dTN3VEtaY3I5d3hzb28KLS0tIDJDS0NVbGNCSmFoVnRnOWNNUWky
            OEdtSlZIODlORmNITkptTi9MOFVqV00KXgCKc68nWvQ/Vg//vRstIPwWXtRP9gkR
            nGlpb0dz9CANw+ShEdS/f6N47Qy0o7KlJuf57ootBehDJDmGf3B04w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-10T03:08:15Z"
    mac: ENC[AES256_GCM,data:Knmnx4bB7dQIZtdbjEEi9roQSqq1gXjp2ddqIKwqxvWlmnLTPtyvWK3e/IP5XnLGmloDB3tCZn7/fDUyiyd5x2R6NG/yP6dTI43GW6z8l5QWUyHXqhhUjuLd4k/tEnTuP0TuiGAoROVgWgnpmD8EzE/5kwZTLeWh+0NxJ5y0nh4=,iv:zTUen7GleWZDAzV10MuI6NV0tJG4Bov+2gMrMFOV7d4=,tag:CEoyysOLJDVQegYsmPgmiA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
