apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:Z7O9XGRpG+Eqglyi7E+WWfVeVKo0iWLi1pMCAepQVnYYII0d9ncEOA==,iv:1lecSLu6ES9/3+svhdL0yD+zFy+Me1ObqFq7v88kJLI=,tag:pssHyotpBeUqjnMDBZ2LqQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15nyeuq0zlhyu80tytvwhjdhmpa5mwnclm454cc0trt7ezxrnk37shpeefh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoVk8xaGNWVklYVUduRHZw
            cUlBTElweVZwZEo3RHZqMk1YeEdxNmE0Umk0CjdKU2xPR0tyLzUwUWt1WVJ0QXBs
            Rnk1bXluWG14UTZOUmNoVXFaVXRpTFEKLS0tIDNBV01RUzNUTjYrZnNhSUNjcTdo
            dDFmb0hRRnVFVUJPL3NsdGNUeWxacjgKG1eV68e8sugfVp66YE4cxfXevMQN4VxK
            oPYo5+3IUZnesGk7zbD/julEl9aSjTuE2fG8tF+0boKwY/ZbR/z7Cg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-09T15:48:24Z"
    mac: ENC[AES256_GCM,data:QHgl/F2ELVXEgph6dL3usQFFMyZqbu/39QpPyoMjW5YANtX1LqvjvqS+Cwcqo91BIvvKe90Yf64c98zVIgodl/OGT45XwN8XPC8eulpKTKtszxN/xe2tF+AbyEW2xdMmuzuzSkgpyjUQhaSh9+K7lwYaTcFCq5UXwDk+u0ttzPU=,iv:LMwblvu01nssLtSAUf+DZ7yXj8OzBLyqtqOovPEWO1s=,tag:ZNcUYS1tnZRX6cld5zoGlQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
