apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:o8vSkWoeYZJnCuunQ4YzZY+8c0zhzJ0Veoo4WxLmP8UWqvPTLErZtQ==,iv:71iq+9mVISEkpCsfsEmSfjEqYyUERbYck7KvsZRKpB8=,tag:Pq68S03YzT+PkZtmCdFKrQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15nyeuq0zlhyu80tytvwhjdhmpa5mwnclm454cc0trt7ezxrnk37shpeefh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrTHVlYlRldXFuWlE2ekFs
            Zk9SODF6VWFmNUlxS2Mvdnl2cVc1ZHIycFI0Cmx0K29PeGtGUGF4bXI4V1RLaW1t
            VlBTbDJGNEpnUmZ0N3M2czhuMzNWNncKLS0tIDVielIxc3VFSU5UMkR4UlZrRmFJ
            QklMSzBpb24zWmY2RWlnTzA0Vmx3WmsKqyVnfg1ciX9b8Tcgt6afi8FqLk1lwbne
            7pPJX6NLbRLSCtNCvPQZmYfxvtcb1FVEM0Hsy6XMvUItvSWS+4Z1uQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-09T20:45:14Z"
    mac: ENC[AES256_GCM,data:wXNBzNJ81oBzUWa32Lh6hzWZgL3A8uJsH0OgPirWDnm/aObAx8S66XTH3uoGcxVhO2L69bDCe6JBSE2LsfO74hPSanNIibyPzL6W+JICiLreL3z7G8l16E7Nw3XIXe4TDbwc2D0vaytBZEp3R6W08zXubYqQgrkxMkuHTVwR8S0=,iv:Fssn3HrD8Erm3hPI6x90zekfkH0gioQ7B//OLW8shPc=,tag:75SBnme5vrpEP0Yygn43dw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
