apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:l2s59UaaxOeVOG57k1xsq3M+KzVpsGjXRxKGvrHMSb0QDsvR7s94UA==,iv:8D2xv8CMWhQGqE7wN4gArARg+x0Dc0gCxQFxXScSKoA=,tag:8LiKqeTfXd0P/5jdcNduyg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15nyeuq0zlhyu80tytvwhjdhmpa5mwnclm454cc0trt7ezxrnk37shpeefh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4QW5WTUJhUDZmL2F3Mi80
            cGFjOHpwYlo4eXIwOE1SS0UwR2NydTZPdEZvCmUvTlIxdTNJMW94QkkrbnJJa2h0
            U004Tk5BNTU4MVdvV3R1ZFE5dDBBdzAKLS0tIE5nRHVsZyszb3hrZkREYXBRVG95
            MHlCVitlc1RaeVlzcis0dTRNSlBzT1UKPKtG1X+i8EN3US9QXJTVsEy6L/qKAv0y
            v9A6WqzK8i6DEnEjIexu3tfvvwIwGm8RF8ZE0XSVG7l70stjTiRKFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-10T03:08:14Z"
    mac: ENC[AES256_GCM,data:7qBmcmLvN+2M839O43nrgJZC3ZTl7PGTmfSEkEv3tjmZQZMXyiR/Z96t9i666JaI/h5S8T2YSNHSZH3bCQIL6Tb5X7p1uc2wNk5V9YEjpNNhfBtI4ZnR9SYfcoOUW4Uc1L6kXzkKBHi0M+L6vQrTPdLtAWGeKlZDdzADCqIC98A=,iv:4MKQFgO3AkCftvRDrMu7igcmDvTKHfxDpEToFbdnvBc=,tag:E6e6tbWwdLBeKON/6ZJD7Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
