---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app akaunting
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      replicas: 1
      strategy: RollingUpdate
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: docker.io/akaunting/akaunting
      tag: 2.1.35
    env:
      APP_URL: http://akaunting.kalde.in
      DB_DATABASE: akaunting
      DB_HOST: akaunting-db.default.svc.cluster.local
      DB_PREFIX: asd_
      LOCALE: en-US
    envFrom:
      - secretRef:
          name: akaunting-secret
    service:
      main:
        ports:
          http:
            port: &port 80
    serviceMonitor:
      main:
        enabled: true
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
        hosts:
          - host: &host "akaunting.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    persistence:
      storage:
        existingClaim: akaunting-storage-v1
        mountPath: /var/www/html/storage
        enabled: true
    resources:
      requests:
        cpu: .5
        memory: 500Mi
      limits:
        cpu: 1
        memory: 1000Mi
