---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud-db-backup
  namespace: media
spec:
  interval: "30m"
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      type: cronjob
      cronjob:
        concurrencyPolicy: Forbid
        schedule: "@daily"
    restartPolicy: OnFailure
    image:
      repository: casmith/pgsqldump
      tag: latest
    env:
      DB_NAME: nextcloud
    envFrom:
      - secretRef:
          name: nextcloud-db-backup-secret
    service:
      main:
        enabled: false
    persistence:
      backup:
        enabled: true
        type: nfs
        server: 192.168.10.3
        path: /volume1/cluster/db-backup/nextcloud
        mountPath: /pgsqldump
