# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: radarr
    namespace: media
stringData:
    RADARR__API_KEY: ENC[AES256_GCM,data:vuhxcuqGW85BSDsz4a3cSRuY5KocDwxumjtTqz4NaACkRUtJ+zGiSDDKImz+sCSh,iv:INc27yWCXURnBUDXLwAy0gde3NvZ93/AuG7xvpxXL0Y=,tag:nbrFf6U9MXBqSZuFtwUGeA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15nyeuq0zlhyu80tytvwhjdhmpa5mwnclm454cc0trt7ezxrnk37shpeefh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCVkljVVZ6T0Z6Z1EvMUZt
            djlWMGlLaXp1RVlFQUJLaDFvUm93YjZOVkhnCnhMdnp6V2dFZmlPVS9zRDl2SmdH
            Z25NRHJXSTB5bnNiaW1hRUlUcHVvNVkKLS0tIG11UC9OOHJDemJVbWhJSE9sTEhH
            a2VNajZwWU5hQkVIWWNxMlpxTjVRR2MKIpMniKFImyip71TTNLTPVcaS2wW+ipON
            RHYF2Py7JVI8rchx4pw7IvZkgQE7pi58ZuARRrOOyxW8++25/jGesg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-19T21:06:41Z"
    mac: ENC[AES256_GCM,data:QH6yu4SkEZunLqvqAjC61MnhjQow0iHlpyN60U3O8LZMGRJarsbvRbQZWvJSgP3WyCOHU/hfUMM+BdoMpv2RyckwENvbLOBqNpevCOczGOJse8EZaSxXVFQDhGnVMhni29k5BcL441y8pM1HzH3JVnMtN/rPsflB3xtpKz/DKpE=,iv:ZPNjFtsMmpUVNo4ZkgLqnhh8w1HktYAmi5F/Deb0wCo=,tag:uDoNvMyXjYMVdWVLO0wDaA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
