---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dispatcharr
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: dispatcharr-celery-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        POSTGRES_HOST: &dbHost postgres-rw.database.svc.cluster.local
        POSTGRES_USER: &dbUser "{{ .POSTGRES_USER }}"
        POSTGRES_PASSWORD: &dbPass "{{ .POSTGRES_PASSWORD }}"
        POSTGRES_DB: dispatcharr
        # Postgres Init
        INIT_POSTGRES_DBNAME: dispatcharr
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: dispatcharr
    - extract:
        key: cloudnative-pg
