---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fireflyiii
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: fireflyiii-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        APP_KEY: "{{ .APP_KEY}}"
        DB_CONNECTION: pgsql
        DB_PORT: "5432"
        DB_HOST: postgres-rw.database.svc.cluster.local
        DB_DATABASE: fireflyiii
        DB_USERNAME: "{{ .POSTGRES_USER }}"
        DB_PASSWORD: "{{ .POSTGRES_PASS }}"
        FIREFLY_III_ACCESS_TOKEN: "{{ .PERSONAL_ACCESS_TOKEN }}"

        # Postgres Init
        INIT_POSTGRES_DBNAME: fireflyiii
        INIT_POSTGRES_HOST: postgres-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
  dataFrom:
    - extract:
        key: fireflyiii
    - extract:
        key: cloudnative-pg
