---
# Master PVs
apiVersion: v1
kind: PersistentVolume
metadata:
  name: seaweedfs-master-0
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.10.3
    path: /volume1/cluster/seaweedfs/master-0
  claimRef:
    namespace: storage
    name: data-storage-seaweedfs-master-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: seaweedfs-master-1
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.10.3
    path: /volume1/cluster/seaweedfs/master-1
  claimRef:
    namespace: storage
    name: data-storage-seaweedfs-master-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: seaweedfs-master-2
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.10.3
    path: /volume1/cluster/seaweedfs/master-2
  claimRef:
    namespace: storage
    name: data-storage-seaweedfs-master-2
---
# Volume PVs
apiVersion: v1
kind: PersistentVolume
metadata:
  name: seaweedfs-volume-0
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.10.3
    path: /volume1/cluster/seaweedfs/volume-0
  claimRef:
    namespace: storage
    name: data-seaweedfs-volume-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: seaweedfs-volume-1
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.10.3
    path: /volume1/cluster/seaweedfs/volume-1
  claimRef:
    namespace: storage
    name: data-seaweedfs-volume-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: seaweedfs-volume-2
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.10.3
    path: /volume1/cluster/seaweedfs/volume-2
  claimRef:
    namespace: storage
    name: data-seaweedfs-volume-2
---
# Filer PVs
apiVersion: v1
kind: PersistentVolume
metadata:
  name: seaweedfs-filer-0
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.10.3
    path: /volume1/cluster/seaweedfs/filer-0
  claimRef:
    namespace: storage
    name: data-filer-seaweedfs-filer-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: seaweedfs-filer-1
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.10.3
    path: /volume1/cluster/seaweedfs/filer-1
  claimRef:
    namespace: storage
    name: data-filer-seaweedfs-filer-1
