apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:Rrp+SgsryBTlV8/jmZEFKw==,iv:3GlCrORLs7tzi3zI9oqEs3XS6x4Xg2wfvHRYU+Y0uEw=,tag:Spp26v0gdxu04d5xOxPj2w==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:6hFHOS6ra2jR80x3MdvjhwnfJfSDvfic9xy+B7Bm3G7iUJ5S,iv:2pn/G0353wHbK7vrjOuLMugeeHNooyvusz+fSBCfpUU=,tag:nGkAoySlTo15/qrn44NBdA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:Yk0NlIysHyA=,iv:TfHbYh8/2KdWgyxcjn4EviHsPrra8cu5brG5C/jSv+o=,tag:bzP1661FvRVUrVufiS0s2A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15nyeuq0zlhyu80tytvwhjdhmpa5mwnclm454cc0trt7ezxrnk37shpeefh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjQ25xaXVuR0RMWEh4MjRz
            Rm1oWXEwSGZndm4xNlArbC8ySndUaS9NU2hJCk95K3N5aUQvNDFXNmpGVS9VUmRN
            WGtXWnN0MUhPVDZVcVRCdGcrZzBZREEKLS0tIGdxNEcxVzFLMk9ic1ZjTi9uNTJE
            aWFQZ25FTCtSb2RobXdoV0lpL1JwN0UKXT61IW3PGyT+MEfKR1sjS0wQ2zOey7We
            PsobC/HINWDB+qiRQeWvgx8P9HEpEjK82g+gAB4DXUerixYa8QPeVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-10T03:08:14Z"
    mac: ENC[AES256_GCM,data:hpUr86s1qTQtREUVtGER3cIAv5eF89X2b1YEtvHd0g1jszuN9KamcQD9FF87KyqdtPwkuezrwikrH4sxlocN+ha9WeK9UwHs3ameufzbSypOCGSuLAqOmsjnWVmXKQHlS7UvLxXK2NfyIuQEWZcaRn8ThzZ3PJ0ThAA5Aov1GUY=,iv:EXu85CJQ2/MbApEN9IhpAPns8YKF9PhbIH5kSLpzxcA=,tag:Qad0rNByTvB2GO5Gk9sIDA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
