apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:JtdN7AKBs0vlw99EH3sYdQ==,iv:DKJLZ7U3o/ddlZozg2GXVpr8LPAOJ3mZfYBlSTOrwH0=,tag:6hKTQ8zsl0snz6fnfbKqHA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:AbOjXo+/9XiyNW0ll0BKVbgDh+4f/0uo9ejbBaYOv6cK6tSU,iv:ZMKPGtBus3fH2Wt8n0GMgTYeTVSe1NLMr8V+Z/DDWnA=,tag:bQP18mI+NkyverYpKxQVlw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:NGCASJUd4ZY=,iv:uCuXXWhSWysaAM7I1n+IcLGd09TDbdyQKECBxjQmBSU=,tag:p3nMao2AScPPtF2ne00q7w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15nyeuq0zlhyu80tytvwhjdhmpa5mwnclm454cc0trt7ezxrnk37shpeefh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKZFhSZXlRUGtsTzZHQUND
            R3hxZWIxb0lsb3d6VmNtSDRwZThOZmRDM0ZBCnBhR0JFREJBU2tld3MvYmwyR2Q0
            NVBYZjVjS0hSYThVcVVLcnMzZTRHQjQKLS0tIHZuak51dXYwd2JFUTg1aDhRRFBV
            T0ZBdG1pcGJlMWUzV2FYZC9nYjF5TnMKc15/y8vjVo4Tm+hZ2XxSdIhXeY4rS8J4
            rdYEE60ssevlQCyA16RwcNcVgvAQYa4idjPz6xUBu+cEz10fcc0OVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-09T20:45:14Z"
    mac: ENC[AES256_GCM,data:+G0QPLLm7mT0w+ib5m25mTrS0EQ61VtXzHC4h3I3F3JmKMomZD77HVBXgG3550vnlb7f1k4Oi53iLyMrk7bLUTgv3VNL75Ih7DxJHPNFLszn9oUVEyO4wYVlayoEciZVB3WTIDGqDNVxhM8PuBw/0lqcFGw1+o4DK6C8Ua7ynww=,iv:MtouZKJe7MCgjKuZCjroRvZqFsGYQLgVWiWQzU4aTOg=,tag:1cUyOIXvbfM/Fnd193447Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
