apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:YUSnpsgC9VYSI4FZqVA/9g==,iv:N2b9EpmvdIPQCWjm9IlYo4ooBvDMTzItI7Dq2sQJE74=,tag:LvHKTsdJJQY61FGyuv0nwQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:Y555c3t/iJFN63/jFOFNosHKK/3WQ2wtI259ezg4bC5xfZBB,iv:ByjDqO/XJzAEmcqmPaZESu6+CRpzduVwtgwDsuVb1i4=,tag:B/n5JJ9+sBHregU25o0bYQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:hXpinHn8S0c=,iv:tEQz2d8Nhd4WwsAhP8mKUm8aUs6guQyoQH+5cLLWmwY=,tag:Q2zCFLCVZm3aJCXlbD0etw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15nyeuq0zlhyu80tytvwhjdhmpa5mwnclm454cc0trt7ezxrnk37shpeefh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzSFlxT2xxb3VXQUNYMk01
            cmxzb0VBM2g4cFFRemtDVk5jcWRqRGZCem1BCnNxdUIveHk2bmU1Y0U5c1hyYjF0
            dkZEU2lUZ0IrQkxwR2ZlNWg1QlJMbXMKLS0tIEZvaE9lSnM5b2hqVDFEL2UxMFd5
            MDIzTVBtcGd6SlVwUUhiNDVRL3o5MGcKvVI4PfF4D5bs3YUd+eMm06PE175XMMdO
            dFEap2+PEDH3gB8mLtZFt3UdEt5dLNlpXf1wviszjMFUfPh6gAYu9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-09T15:48:24Z"
    mac: ENC[AES256_GCM,data:Nbr8Kr2pa2ayPuEtvtwfGOTqFsUkQIzvwv7rp8eZ+Tb/jWWeEF2T6dUNYrMFnYSGnwBRGXQl7+VciFfPbMg0FAkFuiCdrMgZB9NfjK2AqIEUZqYxuS5WRAimFHgV1ixdCGNtE9/Np387zHVP34cgO4XDrLAx3Cgu+Nl9MjsM2vU=,iv:KX08HlWjOQN2TFVVDuMISrF59GIbhV13O3UutNv4ZJM=,tag:LDMIX+eExV9Pz+6bXzKEJw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
