---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app kapowarr
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      replicas: 1
      strategy: RollingUpdate
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: mrcas/kapowarr
      tag: v1.2.0
    service:
      main:
        ports:
          http:
            port: &port 5656
    serviceMonitor:
      main:
        enabled: true
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
        hosts:
          - host: &host "kapowarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    persistence:
      db:
        enabled: true
        type: nfs
        server: 192.168.10.3
        path: /volume1/cluster/kapowarr
        mountPath: /app/db
      downloads:
        enabled: true
        type: nfs
        server: 192.168.10.3
        path: /volume1/downloads/complete/comics
        mountPath: /app/temp_downloads
      comics:
        enabled: true
        type: nfs
        server: 192.168.10.3
        path: /volume1/share2/comics
        mountPath: /comics

    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 750Mi
