apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:AgYxKcpqfp0w69SaB4cu17vXTVX/YkPzs5zVc21q31GTzpdH,iv:tgtCqzICsfcEB3vIe5aX998Vfvt1YuMLM9egco0mOfo=,tag:i0BrTcCE3ap0FXVj3JzTnQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:NNL57HlBUHnOZaT6tQcx8X7Y/SZFgpe/4XjrBS4IrasFpk3AWynuwmU8ahYTu59wLgAh0Dtp8w0jp+bT3B6E7+Z4i5W7qZ52yRdfIdYNRibgqk44Vxk5KVTNJ4AEE/X7EySLG/v80SUssNSCqJVXY2kFmX311e9SC4/+Q1SyV1wPckMSS/fAE9NSE0QryGggiX/N3dnIlaxHpJg2fJHj7FFoaBzLteVU1plq2WKDnA==,iv:1Rv8dkVLCD961xgy6WM8vFuZ88FU89WgfoDgcVYwVXo=,tag:7ITGb+zBBu9ADTK/qRqe1A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15nyeuq0zlhyu80tytvwhjdhmpa5mwnclm454cc0trt7ezxrnk37shpeefh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhYkhpY1g1WTZBZTh3MHlh
            RlFlN3pPL003SWgrOUFxUHZPbHgzblpDa0JJCjZOSGlJb1pzN0lKZTB2VFlscEh5
            dGE2UUlsQit1dmtSSlB0TGdIRGhhbE0KLS0tIERscHA3eTJCdXM4aWZsUkc4c3ov
            eks4UzczczRuTGE2ZGN0dzhYbXNXdlEK21FCtJSDmklA//bG1wjqVvfrCsLcN0/A
            uC3QqEOoj/c5AO482dHYIW0YC1LI777uqekwrQj+gADipAbTEP40xQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-09T20:45:14Z"
    mac: ENC[AES256_GCM,data:uNzjqcoS0v7oWLNP3WKxhRRoRV0233tZr4jzLsni2U9NoIBjDl07URFhkYirCxk/hPkok68omspNFbk8kVQtnGZjERdr0/HLALl466rMUgM7YP6ZP2MRaP7D+rLUZelvrruCi0Sqgt2UBL/92hLAnHfjCj8sft0yNT7L1ENa5gM=,iv:6dv83C7PatmCY7werGfEDk/8pS5xLTQpivIAn2MSgCw=,tag:j4eMg/uzzxZFZF1/Kdo8sQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
