apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:mI/zc/hragdPEV2VyrlrUEpM+J4qDO/lTffAzt6jlHbc5iSn,iv:wcxxobYwTuC5tjeGdu1/x0z5ruhq57KwDUbuKZG+JKQ=,tag:ec57v/+6l2kywoG/71p9lA==,type:str]
    credentials.json: ENC[AES256_GCM,data:ZS2n8Unu5EPeWJEsJXm72KUX+Oj0Tr558UsFztYkss1R/8WPrzawn4RchwtcB4cKmZJyeX/WA9Y04iTpQtoiuSSesv/Zuy3xBLRZ2C48Lc9QrrXV6nFZ1aAQ2F/JM4eoz2R6bg7+I2eXtPY3aZ/y4LqX3SZOcm2SvyJ1YIu5dQTHp/VYKT8xaCNaqQS5Mc90dzDGRNe6OnyikLyWFP01wHcmIDP6PBh/0Cs0K+c0QA==,iv:tQLK85gfi73bt9w3CP7AS/3U1BBFNYRdtQWnQPS7uVE=,tag:vSMlmwsWIA+UNNFkM/+OLA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15nyeuq0zlhyu80tytvwhjdhmpa5mwnclm454cc0trt7ezxrnk37shpeefh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3RXVRY2FBSSsrUmV0TTZ6
            Z0pTOWNzUEdPZGRkZ0ZkY3ZDSGNsUUNpcUNjCmlTK3NPRmZLT3pYT0hsVTdGbGdh
            aVFnV1pRYWN6MGpVaDJBSzF3NmM4UTgKLS0tIFI3ak5CdFhwV1BqYVpJVjVuSjBs
            bEVVazhYdE1XcTNGNGZzL2ZlaTNNcjQKpxfA3VOdDeV5qEf/NBgRLn7DQ4H7Z1o2
            Ws49CfTJq1+tazzwymFRJ4308pJK1A2PBk6IdRKuLQCtK44Ut9+Kuw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-10T03:08:14Z"
    mac: ENC[AES256_GCM,data:gQIC0sZpLahYnGuFhq9xf98UeUdhF95dTbTk6qrtBK8CxuBL0vxEE+VWHhRz3cJcwVCuG6xWa62VQF3DRxrjUwRz18O7PIZ/zdYuTcnquuW5YECxrExeeAjKvluRCjn5jfHRPIR8xIdvhOpEG/1IEcLcTcTu7RMlQqvIRONqYWg=,iv:ZcyecHxtWTN/rmaqlf9Kf6WfdmC94iHo3KYh8M2+VsI=,tag:X9jaEcTnI5yo0lJYLyFfGw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
