apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:UL/9hkAX8fhaGBkN30EFfySTeAekIH/FI77LiDtoTXQxyMTr,iv:e994b1zjOxgfD8j2kb4a9QuNrObw0pgmvn00mXaPPT0=,tag:VEvJcKCVSAboWZ2Vw5loKw==,type:str]
    credentials.json: ENC[AES256_GCM,data:GBRqoECDc/z7FudN7hAF0IXWkl36gu5EXykFChQXn2dYeK0MiGd+FDPhwGFBzcUmrnFmxebmtEqbOMUky6EIKe+uG2OaFIouf2ie0HqDGTkSC83iMHq5Ab8wEHbsZpS+f+kFm3UyD3ImCmGEM4Dw1S7oCw6Q7GFxlb1piclPTHApWvNwTLQ8fWuFDTAk/3plTF8Iak/pcVwRc0yPjFqWLv8ehtEZywr8fPmiBr9oqQ==,iv:WEBQTZbGxbDQG+7CRXLHqaihPOIq12PGcKIguhqdEa8=,tag:LTkZQ/RKTBtXM0ubbXadpA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15nyeuq0zlhyu80tytvwhjdhmpa5mwnclm454cc0trt7ezxrnk37shpeefh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIWEZzYmlBRXNkYXZrSnJL
            RU1JQlYyYnNtSjhSREZURkNsU1MwdDZRYUFzCmZvSEthWlF4RlpWMFZLMTRaL240
            TFY1WEd6T0YvdGQ0d3FOVFBvYVV1THMKLS0tIFJ3SW9hSlh5b0lEUFFKUW1PZjlM
            c1FpeDQ2QVhnQVFVa1hyZkVaRm8xQkkKEcWab9UNFeNZHJb0B83XvtLQV7/sp+Ao
            N49kWQFT9fog8vO0tTQhyiz2znIyDEBHfbZ85fKy1vo7B3rWjs+XPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-09T15:48:24Z"
    mac: ENC[AES256_GCM,data:QDQ2/uklCmlRipY8B0e8Ti9AEwcrSprKWwexAJdanA5TngEbfhqQciDclhEHc2H/qZeMgTZDGp7J6XhxBnKtgtm1UVmeQ5bXqVAPIM5WdLMkCZndiHK38dBufndXIpNTIHqDAR8N03eU04q26aIOuEPF9JJPEGO5bGffM989zGI=,iv:6EtcmGI999W9UJIDUmqmCx1Ol4ZydhMgBpjuwU772gI=,tag:1peC4ZOXdICI/BMMhpeAjA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
