---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dailytxt
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: dailytxt-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        SECRET_TOKEN: "{{ .SECRET_TOKEN }}"
        ADMIN_PASSWORD: "{{ .ADMIN_PASSWORD }}"
  dataFrom:
    - extract:
        key: dailytxt
  refreshInterval: 5m
