---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-dispatcharr
  namespace: flux-system
spec:
  path: ./kubernetes/apps/media/dispatcharr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  dependsOn:
    - name: cluster-apps-cloudnative-pg-cluster
    - name: cluster-apps-external-secrets-stores
    - name: cluster-apps-dispatcharr-redis

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-dispatcharr-celery
  namespace: flux-system
spec:
  path: ./kubernetes/apps/media/dispatcharr/celery
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  dependsOn:
    - name: cluster-apps-cloudnative-pg-cluster
    - name: cluster-apps-external-secrets-stores
    - name: cluster-apps-dispatcharr-redis

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-dispatcharr-redis
  namespace: flux-system
spec:
  path: ./kubernetes/apps/media/dispatcharr/redis
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  interval: 30m
  retryInterval: 1m
  timeout: 3m
